apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: secure-coding-dojo
  creationTimestamp: null
  name: secure-coding-dojo-insecureinc-oauth-proxy
  labels:
    secure-coding-dojo: oauth-proxy
    app: secure-coding-dojo-insecureinc-oauth-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-coding-dojo-insecureinc-oauth-proxy
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        secure-coding-dojo: oauth-proxy
        app: secure-coding-dojo-insecureinc-oauth-proxy
    spec:
      containers:
      - args:
        - --provider
        - oidc
        - --oidc-issuer-url
        - [KEYCLOAK URL]
        - --client-id
        - secure-coding-dojo
        - --client-secret
        - $(client_secret)
        - --http-address
        - :8080
        - --upstream
        - http://secure-coding-dojo-insecureinc:8080
        - --cookie-secure
        - "true"
        - --email-domain
        - "*"
        - --cookie-secret
        - $(cookie_secret)
        - --skip-provider-button
        - "true"
        env:
        - name: client_secret
          valueFrom:
            secretKeyRef:
              name: secure-coding-dojo-oauth2-client-secret
              key: secure-coding-dojo-oauth2-client-secret.txt
        - name: cookie_secret
          valueFrom:
            secretKeyRef:
              name: secure-coding-dojo-cookie-secret
              key: secure-coding-dojo-cookie-secret.txt
        image: quay.io/oauth2-proxy/oauth2-proxy
        imagePullPolicy: "IfNotPresent"
        name: oauth-proxy
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      automountServiceAccountToken: false
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: secure-coding-dojo
  creationTimestamp: null
  labels:
    app: secure-coding-dojo-insecureinc-oauth-proxy
  name: secure-coding-dojo-insecureinc-oauth-proxy
spec:
  ports:
  - name: ui
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: secure-coding-dojo-insecureinc-oauth-proxy
  type: ClusterIP
status: {}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: secure-coding-dojo-insecureinc-secure
  creationTimestamp: null
  namespace: secure-coding-dojo
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`insecureinc.[MY_DOMAIN]`)
      kind: Rule
      services:
        - name: secure-coding-dojo-insecureinc-oauth-proxy
          namespace: secure-coding-dojo
          kind: Service
          port: 8080
  tls: {}
