# Sets up permissions to access dashboard via clusteradmin user
# https://unofficialism.info/posts/accessing-rbac-enabled-kubernetes-dashboard/
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clusteradmin
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusteradmin-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: clusteradmin
  namespace: kube-system
