apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ctf-deny-ingress
  namespace: ctf
spec:
  podSelector:
    matchLabels:
      ctf: challenge
  policyTypes:
  - Egress
  egress: []
